Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2021-12, with the labels that each got.

#41 Update preview version in golang csharp package
  pipeline/generate-preview-golang-csharp-package.yaml
Labels: size/XS

#40 feat: add script for generating java package
  CreateJavaPackage.sh
  Dockerfile
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/M

#42 add java package for staging
  pipeline/generate-java-package-v3.yaml
Labels: size/M

#43 Force angular packages to use string enums
  CreateAngularPackageV3.sh
  pipeline/generate-preview-package-v3.yaml
  pipeline/generate-preview-package.yaml
Labels: size/XS, approved

#44 Update angular build step versions
  pipeline/generate-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
Labels: size/XS
