Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2021-11, with the labels that each got.

#28 Add golang preview package generator
  pipeline/generate-preview-golang-package-v3.yaml
Labels: size/M, approved

#29 update csharp package
  CreateCsharpPackage.sh
Labels: size/XS

#30 update pipelines
  pipeline/generate-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS

#31 revert target for charp generator
  CreateCsharpPackage.sh
  pipeline/generate-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS

#32 revert changes to CreateCsharpPackage
  CreateCsharpPackage.sh
  pipeline/generate-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS

#33 revert pipelines
  pipeline/generate-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS

#34 charp emit default values
  CreateCsharpPackage.sh
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/S

#35 Create preview-golang-csharp-package.yaml
  pipeline/generate-preview-golang-csharp-package.yaml
Labels: size/M, approved

#36 Update golang csharp generator, change address
  pipeline/generate-preview-golang-csharp-package.yaml
Labels: size/XS

#37 Update generate-preview-csharp-package.yaml
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS

#39 revert-changes
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS
