Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2022-08, with the labels that each got.

#62 chore: use openjdk11
  Dockerfile
Labels: size/XS, approved

#59 Handle both openapi.json & swagger.json for release pipelines
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-package-v3.yaml
  pipeline/generate-package.yaml
Labels: size/M

#60 fix: add version num,ber to c# preview package gen
  pipeline/generate-preview-csharp-package.yaml
Labels: size/XS, approved

#64 chore: add Skisocks to owners
  OWNERS
Labels: size/XS, approved

#63 fix: generalise script for any package
  CreateJavaPackage.sh
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/XS

#65 fix: remove main pipeline too
  pipeline/generate-java-package-v3.yaml
Labels: size/XS, approved

#66 feat: update image java
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/XS, approved

#67 fix: java semantic naming (first letter lowercase)
  CreateJavaPackage.sh
Labels: size/XS, approved

#68 chore: update java image -> 0.4.1
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/XS, approved

#69 fix: make service lower case java package
  CreateJavaPackage.sh
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/XS, approved

#71 chore: update java image -> 0.4.3
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
Labels: size/XS, approved

#72 chore: add lowercase to release pipeline
  pipeline/generate-java-package-v3.yaml
Labels: size/XS, approved

#73 chore: add updatebot label for python package gen PR
  pipeline/generate-python-package.yaml
Labels: size/XS, approved

#75 chore: get schema from staging if not found
  pipeline/generate-python-package.yaml
Labels: size/M, approved
