Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2022-06, with the labels that each got.

#56 Feat/Python Schemas Generation and PR in `mqube-ml-doc-pipeline-schemas` repo
  pipeline/generate-python-package.yaml
Labels: size/S

#55 chore: initial pythonGen setup for testing
  pipeline/generate-python-package.yaml
Labels: size/M, approved

#58 fix: remove wild card import in python __init__.py files
  pipeline/generate-python-package.yaml
Labels: size/XS
