Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2022-11, with the labels that each got.

#84 fix: use container from the correct location
  pipeline/generate-python-package.yaml
Labels: size/XS, approved

#85 chore: add infrastructure owners to charts and .lighthouse dirs
  .lighthouse/OWNERS
Labels: size/XS

#88 chore: rename pipeline build-push-DANGER
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#87 refactor: use script to locate openAPI spec and general tidy
  Dockerfile
  FindOpenAPISpec.sh
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-package-v3.yaml
  pipeline/generate-package.yaml
  pipeline/generate-preview-csharp-calcvalues-package.yaml
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-golang-csharp-package.yaml
  pipeline/generate-preview-golang-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
  pipeline/generate-preview-package.yaml
Labels: approved, size/L

#89 chore: bump packages
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-package-v3.yaml
  pipeline/generate-package.yaml
  pipeline/generate-preview-csharp-calcvalues-package.yaml
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-golang-csharp-package.yaml
  pipeline/generate-preview-golang-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
  pipeline/generate-preview-package.yaml
Labels: approved, size/S

#90 fix: ignore /bin dirs for C# services
  FindOpenAPISpec.sh
Labels: size/XS, approved

#91 chore: bump packages
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-package-v3.yaml
  pipeline/generate-package.yaml
  pipeline/generate-preview-csharp-calcvalues-package.yaml
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-golang-csharp-package.yaml
  pipeline/generate-preview-golang-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
  pipeline/generate-preview-package.yaml
Labels: approved, size/S
