Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2022-09, with the labels that each got.

#76 fix: Preview packages to openapi
  pipeline/generate-preview-csharp-calcvalues-package.yaml
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-java-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
Labels: size/M, approved

#78 fix: variable naming
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-package-v3.yaml
Labels: size/XS, approved

#80 chore: install gh cli using official method
  pipeline/generate-python-package.yaml
Labels: size/XS
