Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2023-07, with the labels that each got.

#141 chore: python Extra fields ignore
  Dockerfile
  pipeline/generate-python-package.yaml
Labels: approved, size/S

#143 chore: add some temp logs
  pipeline/generate-python-package.yaml
Labels: size/XS, approved

#144 fix: some fixes in replacing python schema configs
  pipeline/generate-python-package.yaml
Labels: size/XS, approved

#146 fix: add unix timestamp to version if already exists
  pkg/packageGenerator/angular/generator.go
Labels: size/M, approved
