Repository spring-financial-group/jx3-openapi-generation, pull requests merged in 2023-04, with the labels that each got.

#113 feat: add initial README
  README.md
Labels: approved, size/L

#115 feat: set version on all old-style pipelines
  pipeline/generate-csharp-package-nonapigw.yaml
  pipeline/generate-csharp-package.yaml
  pipeline/generate-java-package-v3.yaml
  pipeline/generate-package-v3.yaml
  pipeline/generate-package.yaml
  pipeline/generate-preview-csharp-calcvalues-package.yaml
  pipeline/generate-preview-csharp-package.yaml
  pipeline/generate-preview-golang-csharp-package.yaml
  pipeline/generate-preview-golang-package-v3.yaml
  pipeline/generate-preview-java-package-v3.yaml
  pipeline/generate-preview-package-v3.yaml
  pipeline/generate-preview-package.yaml
Labels: approved, size/S

#112 feat: update package generator
  .lighthouse/jenkins-x/generate-test-packages.yaml
  .lighthouse/jenkins-x/triggers.yaml
  Dockerfile
  configuration.ts
  mocks/swagger.json
  openapitools.json
  pipeline/generate-packages-testing.yaml
  pkg/packageGenerator/angular/generator.go
Labels: size/XXL

#118 feat: moving packaging files into the Docker image
  .gitignore
  Dockerfile
  README.md
  cmd/app/main.go
  mocks/registry/.npmrc
  mocks/registry/package.json
  pipeline/generate-packages-testing.yaml
  pipeline/generate-packages.yaml
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generate_packages.go
  pkg/domain/file.go
  pkg/file/file.go
  pkg/packageGenerator/angular/generator.go
  pkg/packageGenerator/base_generator.go
  pkg/packageGenerator/csharp/generator.go
  pkg/packageGenerator/java/generator.go
  templates/angular/.npmrc
  templates/angular/package.json
  templates/angular/tsconfig.json
  templates/csharp/nuget.config
  templates/java/build.gradle
Labels: size/L

#119 fix: version command output
  Makefile
  cmd/app/main.go
  cmd/main.go
  go.mod
  go.sum
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generate_packages.go
  pkg/cmd/root.go
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/commandRunner/cmdrunner.go
  pkg/domain/mocks/PackageGeneratorFactory.go
  pkg/file/file.go
  pkg/file/file_test.go
  pkg/git/git.go
  pkg/openapitools/config.go
  pkg/packageGenerator/angular/generator.go
  pkg/packageGenerator/base_generator.go
  pkg/packageGenerator/csharp/generator.go
  pkg/packageGenerator/java/generator.go
  pkg/packageGenerator/python/generator.go
Labels: size/L

#120 fix: source env vars in make-build step
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#124 fix: make errors more informative
  pkg/cmd/generate/generate.go
  pkg/domain/file.go
Labels: size/M, approved

#127 fix: init variables in top-level command
  pkg/cmd/generate/generate.go
Labels: size/XS, approved

#126 chore(csharp): update dotnet image
  Dockerfile
Labels: size/XS
